### ISSUE TITLE
Wrong Download Links for GeoIP & IPv4 Addresses in the IPv6 Geoip Database

### ISSUE THREAD

**Issue by acidvegas** [ipapi-is/ipapi#1]
20,195 IPv4 addresses have been found in the IPv6 database.

`ipv6,103.187.240.2,OC,AU,Australia,New South Wales,North Albury,2640,Australia/Sydney,-36.05745,146.92995
ipv6,103.187.240.3,OC,AU,Australia,Victoria,Clyde North,3978,Australia/Melbourne,-38.11667,145.33333
ipv6,103.187.240.4,OC,AU,Australia,Victoria,Glenroy,3046,Australia/Melbourne,-37.7,144.93333
ipv6,103.187.240.10,OC,AU,Australia,Victoria,Yackandandah,3749,Australia/Melbourne,-36.31371,146.83958
ipv6,103.187.240.11,OC,AU,Australia,Victoria,Kilsyth,3137,Australia/Melbourne,-37.8,145.31667
ipv6,103.187.240.12,OC,AU,Australia,New South Wales,Albury,2640,Australia/Sydney,-36.07482,146.92401
ipv6,103.187.240.13,OC,AU,Australia,Victoria,Beechworth,3747,Australia/Melbourne,-36.35828,146.68584`

Also I do not understand these prefixes you have in the IPv4 database. For example:
`ipv4,89.184.80.0/21,EU,UA,Ukraine,Kyivska,Kyiv,09854,Europe/Kyiv,50.45466,30.5238
ipv4,89.184.82.0/23,EU,UA,Ukraine,Kyivska,Kyiv,09854,Europe/Kyiv,50.45466,30.5238`

The `89.184.80.0/21` extends to 2048 IP's going all the way to `89.184.87.255`. Which confuses me because the next line is `89.184.87.255` which falls under that /21 CDIR.

Also noticed a few IPv6 addresses that are single addresses, not using a CDIR notation. Not sure if that is how you meant it to be or not.

Also your download links are backwards on the [geolocation](https://ipapi.is/geolocation.html) page. IPv4 download link points to the IPv6 database.

Great website btw, big props. Would love to do some work with you if you are interested.

**Comment by ipapi-is** [comment]
Hey, thank you very much for this issue.

In the most recent release, all of your issues have been fixed.

> 20,195 IPv4 addresses have been found in the IPv6 database.

Fixed.

> Also your download links are backwards on the [geolocation](https://ipapi.is/geolocation.html) page. IPv4 download link points to the IPv6 database.

Fixed.

> The 89.184.80.0/21 extends to 2048 IP's going all the way to 89.184.87.255. Which confuses me because the next line is 89.184.87.255 which falls under that /21 CDIR.

The database is not cleaned from those duplicates. This is one of the things I am planning to do but it does not have priority. The IP lookup table I use is idempotent, therefore stuff like this doesn't hurt.

**Comment by ipapi-is** [comment]
Thank you.

Fixed in commit: 95d2ff4a0d4ce66aecaee5b190ea0a02841b38e2
