### ISSUE TITLE
Any reason why hostingRanges.tsv.zip was removed recently?

### ISSUE THREAD

**Issue by mieszko4** [ipapi-is/ipapi#5]
Hi,

I've noticed that in https://github.com/ipapi-is/ipapi/commit/f523112de193ac1c57a80793c439f97cfd66cfbc you completely removed `databases/hostingRanges.tsv.zip` and instead in https://github.com/ipapi-is/ipapi/commit/b08d62edafd2208fe25d1b1f3ae616920811650f added `databases/HostingRangesIPv4-Sample.csv`.

Also, I see in README that hostingRanges are available in `https://ipapi.is/data/hostingRanges.tsv.zip`.

Questions:
1. Should I now use `https://ipapi.is/data/hostingRanges.tsv.zip`?
2. Are you planning to add all ranges instead of just sample in `HostingRangesIPv4-Sample.csv`?

**Comment by ipapi-is** [comment]
Hi,

Sorry for the hassle but I made the "IP to Hosting Database" commercial and removed it from the free downloads. You can get it here: https://ipapi.is/hosting-detection.html

I am not planning to make it open source again. Sorry. I spend a lot of time building it and I continuously improve it, so I guess it's fair for organisations to pay for it.
