### ISSUE TITLE
Invalid IP range after update of geolocationDatabaseIPv4.csv.zip on 2024-03-06

### ISSUE THREAD

**Issue by mieszko4** [ipapi-is/ipapi#9]
There are 2 invalid rows because end_ip is `0.0.0.0` and is lower than `start_ip`:
```
start_ip: '60.54.50.0',
end_ip: '0.0.0.0',
country_code: 'MY',
latitude: 2.9679,
longitude: 101.653,
accuracy: 1
```

and

```
start_ip: '60.54.51.0',
end_ip: '0.0.0.0',
country_code: 'MY',
latitude: 2.9679,
longitude: 101.653,
accuracy: 1
```

**Comment by mieszko4** [comment]
@ipapi-is Latest update (from yesterday) still contains these invalid data.

**Comment by ipapi-is** [comment]
Fixed in https://github.com/ipapi-is/ipapi/commit/ec751295c80e502ae8b67cba7f6b7d53e9a71346

**Comment by mieszko4** [comment]
All good now. Thnx!
